# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-05-12 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='default_image',
            field=models.ImageField(max_length=200, null=True, upload_to='', verbose_name='图片'),
        ),
    ]
