# Generated by Django 2.1.8 on 2020-05-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20200518_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='author',
            field=models.CharField(default='无', max_length=50, null=True, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='price',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10, null=True, verbose_name='价格'),
        ),
    ]
