# Generated by Django 2.1.8 on 2020-05-13 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20, verbose_name='日期')),
                ('name', models.CharField(default='无', max_length=200, verbose_name='城市')),
                ('cdi', models.DecimalField(decimal_places=2, default='0.00', max_digits=10, verbose_name='交通拥堵指数')),
            ],
            options={
                'verbose_name': '交通数据',
                'verbose_name_plural': '交通数据',
            },
        ),
    ]
