# Generated by Django 2.1.8 on 2020-05-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20, verbose_name='城市编号')),
                ('name', models.CharField(default='无', max_length=200, verbose_name='城市')),
                ('cdi', models.DecimalField(decimal_places=2, default='0.00', max_digits=10, verbose_name='交通拥堵指数')),
                ('hlrr', models.DecimalField(decimal_places=2, default='0.00', max_digits=10, verbose_name='高延时运行时间占比')),
                ('mrcr', models.DecimalField(decimal_places=2, default='0.00', max_digits=10, verbose_name='拥堵路段里程比')),
                ('speed', models.DecimalField(decimal_places=2, default='0.00', max_digits=10, verbose_name='平均速度')),
                ('rrsdr', models.DecimalField(decimal_places=2, default='0.00', max_digits=10, verbose_name='道路运行速度偏差率')),
            ],
            options={
                'verbose_name': '青岛市交通数据',
                'verbose_name_plural': '青岛市交通数据',
            },
        ),
    ]
