# Generated by Django 2.1.8 on 2020-05-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mapinfo',
            options={'verbose_name': '全国主要城市最近七天内平均交通数据', 'verbose_name_plural': '全国主要城市最近七天内平均交通数据'},
        ),
        migrations.AlterField(
            model_name='mapinfo',
            name='cdi',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=20, verbose_name='交通拥堵指数'),
        ),
        migrations.AlterField(
            model_name='mapinfo',
            name='hlrr',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=20, verbose_name='高延时运行时间占比'),
        ),
        migrations.AlterField(
            model_name='mapinfo',
            name='label',
            field=models.CharField(max_length=100, verbose_name='城市编号'),
        ),
        migrations.AlterField(
            model_name='mapinfo',
            name='mrcr',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=20, verbose_name='拥堵路段里程比'),
        ),
        migrations.AlterField(
            model_name='mapinfo',
            name='rrsdr',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=20, verbose_name='道路运行速度偏差率'),
        ),
        migrations.AlterField(
            model_name='mapinfo',
            name='speed',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=20, verbose_name='平均速度'),
        ),
    ]
