# Generated by Django 2.1.8 on 2020-05-13 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapinfo',
            name='hlrr',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10, verbose_name='高延时运行时间占比'),
        ),
        migrations.AddField(
            model_name='mapinfo',
            name='mrcr',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10, verbose_name='拥堵路段里程比'),
        ),
        migrations.AddField(
            model_name='mapinfo',
            name='speed',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10, verbose_name='平均速度'),
        ),
    ]
