# Generated by Django 2.1.8 on 2020-05-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20200514_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapinfo',
            name='cdi',
            field=models.CharField(default='无', max_length=200, verbose_name='交通拥堵指数'),
        ),
        migrations.AlterField(
            model_name='mapinfo',
            name='hlrr',
            field=models.CharField(default='无', max_length=200, verbose_name='高延时运行时间占比'),
        ),
        migrations.AlterField(
            model_name='mapinfo',
            name='mrcr',
            field=models.CharField(default='无', max_length=200, verbose_name='拥堵路段里程比'),
        ),
        migrations.AlterField(
            model_name='mapinfo',
            name='rrsdr',
            field=models.CharField(default='无', max_length=200, verbose_name='道路运行速度偏差率'),
        ),
        migrations.AlterField(
            model_name='mapinfo',
            name='speed',
            field=models.CharField(default='无', max_length=200, verbose_name='平均速度'),
        ),
    ]
