# Generated by Django 2.1.8 on 2020-05-20 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20200514_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapinfo',
            name='cdi',
        ),
    ]
